<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arduino" nsURI="http://www.obeo.fr/arduino" nsPrefix="arduino">
  <eClassifiers xsi:type="ecore:EClass" name="Hardware" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="platforms" lowerBound="1"
        upperBound="-1" eType="#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//Connector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Platform" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digitalPins" upperBound="-1"
        eType="#//DigitalPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analogPins" upperBound="-1"
        eType="#//AnalogPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ModuleKind"
        defaultValueLiteral="digital"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//Library"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalPin" eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalogPin" eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sketch" eSuperTypes="#//NamedElement #//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardware" lowerBound="1"
        eType="#//Hardware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardware" eType="#//Hardware"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sketch" eType="#//Sketch"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" upperBound="-1"
        eType="#//Platform" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Instruction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Instruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Status" eSuperTypes="#//ModuleInstruction #//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Sensor"
        eOpposite="#//Sensor/status"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Level" eSuperTypes="#//ModuleInstruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" lowerBound="1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleInstruction" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Utilities" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="IO" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//Utilities">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//Time"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Time">
    <eLiterals name="MilliSecond"/>
    <eLiterals name="MicroSecond"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputModule" eSuperTypes="#//Module"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputModule" eSuperTypes="#//Module"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ModuleKind">
    <eLiterals name="digital"/>
    <eLiterals name="analog"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pin" eType="#//Pin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iteration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//ModuleInstruction #//BooleanOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" upperBound="-1"
        eType="#//Status" eOpposite="#//Status/sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//BooleanOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathOperator" abstract="true" eSuperTypes="#//Value #//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//OperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorKind">
    <eLiterals name="equal"/>
    <eLiterals name="minus"/>
    <eLiterals name="upper"/>
    <eLiterals name="lower"/>
    <eLiterals name="plus"/>
    <eLiterals name="diff"/>
    <eLiterals name="upperOrEqual"/>
    <eLiterals name="lowerOrEqual"/>
    <eLiterals name="mul"/>
    <eLiterals name="div"/>
    <eLiterals name="min"/>
    <eLiterals name="max"/>
    <eLiterals name="pourcent"/>
    <eLiterals name="and"/>
    <eLiterals name="or"/>
    <eLiterals name="not"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Value #//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Set" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericalOperator" eSuperTypes="#//MathOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanOperator" eSuperTypes="#//MathOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Library">
    <eLiterals name="none"/>
    <eLiterals name="servo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//BooleanOperator"/>
  </eClassifiers>
</ecore:EPackage>
